--- #YAML:1.0
name: WebService-CIA
version: 1.0
author:
  - Ian Malpass (ian@indecorous.com)
abstract: information from the CIA World Factbook.
license: perl
generated_by: Module::Build version 0.2609, without YAML.pm
