--- #YAML:1.0
name: WebService-CIA
version: 0.02
author:
  - Ian Malpass (ian@indecorous.com)
abstract: information from the CIA World Factbook.
license: perl
generated_by: Module::Build version 0.2607, without YAML.pm
